In [6]:
import numpy as np
import gym 
import random

In [17]:
env = gym.make("FrozenLake-v0")

In [18]:
action_size = env.action_space.n
state_size = env.observation_space.n

In [19]:
qtable = np.zeros((state_size, action_size))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
total_episodes = 15000
learning_rate = 0.8
max_steps = 99
gamma = 0.95

epsilon = 1.0
max_epsilon = 1.0
min_epsilon = 0.01
decay_rate = 0.005



In [12]:
rewards = []

for episode in range(total_episodes):
    
    
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        
        
        exp_exp_tradeoff = random.uniform(0, 1)
        
        if exp_exp_tradeoff > epsilon : 
            action = np.argmax(qtable[state, : ])
            
        else :            
            action = env.action_space.sample()
            
        
        new_state, reward, done, info, = env.step(action)
        
        
        qtable[state, action] = qtable[state, action] + learning_rate*(reward + gamma * np.max(qtable[new_state,:]) - qtable[state, action]) 
        
        total_rewards += reward
        
        
        state = new_state
        
        
        if done == True :
            
            break
        
    epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate * episode)
    rewards.append(total_rewards)
print("Score over time : "+ str(sum(rewards)/total_episodes))
print(qtable)
        
    
    
    


Score over time : 0.47886666666666666
[[4.28036287e-01 9.48313623e-02 9.91199914e-02 8.94115302e-02]
 [1.45816936e-03 5.30544310e-03 7.21417180e-03 1.00459660e-01]
 [1.14862479e-02 9.08063239e-03 1.25304891e-02 3.45365361e-02]
 [4.57591848e-03 6.13968926e-03 3.94970516e-03 3.12845545e-02]
 [5.64665602e-01 4.78619118e-02 1.39751502e-03 2.00345170e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.38875568e-06 2.46074561e-06 1.03040565e-02 2.19528559e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.79862215e-02 2.58583987e-02 2.21017039e-02 7.40768578e-01]
 [4.50965607e-02 8.47592634e-01 4.66505977e-05 5.12416531e-02]
 [2.21150071e-01 4.23165532e-04 1.15889229e-03 4.71388556e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.26181393e-01 8.45590066e-02 8.53212240e-01 1.64399020e-01]
 [2.29674378e-01 9.71063678e-01 2.77401794e-01 5.17088090e-01]
 [0.00000000e+00 

In [16]:
env.reset()


for episode in range(5):
    
    state = env.reset()
    step = 0
    done = False
    
    print("*"*20)
    print("Episode : ", episode)
    
    
    for step in range(max_steps):
        
        action = np.argmax(qtable[state, : ])
        
        newstate, reward, done, info = env.step(action)
        
        if done:
            
            print("Number of steps : ", step)
            break
            
        state = new_state
env.close()
        
        
    



********************
Episode :  0
Number of steps :  48
********************
Episode :  1
Number of steps :  13
********************
Episode :  2
Number of steps :  15
********************
Episode :  3
Number of steps :  55
********************
Episode :  4
Number of steps :  7
